[package]
name = "gliua"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "gliua"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
ecow = "0.2.2"
rustler = "0.32.1"
uiua = { version = "0.10.3", default-features = false, features = ["batteries"] }
