[package]
name = "glua"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "glua"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.32.1"
uiua = { version = "0.10.3", default-features = false, features = ["batteries"] }
